### ISSUE TITLE
consumer 客户端中途断开，导致消费的消息总数和生产的总数不一致问题

### ISSUE THREAD

**Issue by luoyjx** [ali-sdk/ali-ons#15]
版本：2.0.3

请问，在 consumer 订阅后，Ctrl + c 退出前，做了 `consumer.close()` 操作，但是消费的消息总数不正确了，可能是什么原因引起的呢？

并且还有一个现象是后续的消费情况不太均衡了。

**Comment by gxcsoccer** [comment]
能提供重现代码吗？

**Comment by gxcsoccer** [comment]
没看太明白

**Comment by luoyjx** [comment]
额，忽略这个 issue 吧 ... 我还在本地找原因中 ... 看了下 ali-ons 的代码，退出时 close 掉的时候会保存 offset ，可能是我哪里没有处理好吧，如果我定位到具体的问题再重开 ... 不好意思啦~
