### ISSUE TITLE
这个 sdk  目前支持分区顺序消息的 sharding key 么？

### ISSUE THREAD

**Issue by luoyjx** [ali-sdk/ali-ons#16]
sdk 版本: 2.0.3
node 版本: 8.4.0

需要根据某个属性做 sharding ，但是在 sdk 中似乎木有找到 sharding 功能相关的选项，不知道这个 feature 现在有支持不？

**Comment by gxcsoccer** [comment]
提供 java sdk 相关的示例代码，或者文档，我看看

**Comment by luoyjx** [comment]
我是看到这个文档的示例中有 sharding key 支持

**Comment by gxcsoccer** [comment]
恩，这个应该比较好支持，后续支持

**Comment by luoyjx** [comment]
赞，期待！
