### ISSUE TITLE
[BUG] 阿里云 ONS 后台消息验证功能，在消费节点正常连接的情况下，报验证失败。

### ISSUE THREAD

**Issue by plusmancn** [ali-sdk/ali-ons#18]
在阿里云后台点击 `消息查询->按 Topic 查询`，选择某条历史消息，点击 `消息详情`，假如当前 `topic` 下有消费机在线，你能看到如下界面

![image](https://user-images.githubusercontent.com/4994682/50277956-cc371e00-0480-11e9-8615-4812e1c46130.png)

此时点击消费验证，会出现如下界面，在这里我们可以选择特定的机器进行消息验证

<img src="https://user-images.githubusercontent.com/4994682/50277906-a578e780-0480-11e9-80ac-25bb7b7d0906.png" width="60%" />

但是系统会返回如下报错，事实上消费机是能够收到消息，并且正确消费的，如第一张图所示。
消息验证的功能，对于系统接入调试很有帮助，怀疑消息验证的的协议当前 SDK 还未实现。

![image](https://user-images.githubusercontent.com/4994682/50278116-20420280-0481-11e9-9c01-6f8f4bfdfba4.png)

**Comment by gxcsoccer** [comment]
@plusmancn 能提供一些截图吗？

**Comment by 18679979446** [comment]
消息消费后在阿里云消息轨迹查询依然是尚未消费，请问如何正确的返回已消费信息？
![image](https://user-images.githubusercontent.com/16495287/49921663-439d0880-fee9-11e8-9c97-2a803dcb9417.png)

**Comment by gxcsoccer** [comment]
@plusmancn 欢迎 PR 👍

**Comment by plusmancn** [comment]
@gxcsoccer 请问有一些协议文档可以参考嘛，我们这边只能手撕 Java 客户端。

**Comment by denghongcai** [comment]
> @gxcsoccer 请问有一些协议文档可以参考嘛，我们这边只能手撕 Java 客户端。

我们也是手撕的= =
