### ISSUE TITLE
项目目前进展如何, 有重启打算吗?

### ISSUE THREAD

**Issue by sandwich99** [ali-sdk/ali-ons#2]
最近使用 ali-ons 提供的 http 方式接入, 吞吐量太差. 达不到预期.

期待官方继续开源 nodejs sdk

**Comment by XadillaX** [comment]
@sandwich99 https://github.com/xadillax/aliyun-ons 可以先使用这个垫垫肚子

**Comment by gxcsoccer** [comment]
已经正式发布，欢迎使用
