### ISSUE TITLE
并发性能

### ISSUE THREAD

**Issue by JacksonTian** [ali-sdk/ali-ons#23]
我当前的consumer，单进程下，系统资源消耗 ～100M 内存，20% CPU，TPS 只有 30-40/s，并发性明显不够。

**Comment by gxcsoccer** [comment]
@JacksonTian 老师帮忙改下呀

**Comment by JacksonTian** [comment]
codebase 较大，没有太多集中的时间来改。

**Comment by denghongcai** [comment]
拉一批消息下来以后，处理是串行的，这里影响了并发性。我来改下吧。

**Comment by denghongcai** [comment]
#56
