### ISSUE TITLE
重试与死信队列支持

### ISSUE THREAD

**Issue by royalrover** [ali-sdk/ali-ons#34]
目前的重试好像是在consumer端的循环，并没有发送类似于RECONSUME_LATER的消息；另外，死信队列现在是不是也不支持呢？

**Comment by anxinghuang** [comment]
同问
![image](https://user-images.githubusercontent.com/41978210/43649912-fafc8f36-9770-11e8-9815-0ec8a6c4a7e7.png)

**Comment by denghongcai** [comment]
是的，欢迎 PR

**Comment by gxcsoccer** [comment]
死信队列 是只 retry message 吗？如果是的话，这里可以支持下

**Comment by royalrover** [comment]
dead message queue，dlq

**Comment by denghongcai** [comment]
@gxcsoccer 这个我昨天正好在实现了

**Comment by gxcsoccer** [comment]
已支持
