### ISSUE TITLE
Unit Test

### ISSUE THREAD

**Issue by zhongjixiuxing** [ali-sdk/ali-ons#35]
跑本地的单元测试不通过, 而且是很简单的配置错误, 这样的代码质量令人堪忧
![image](https://user-images.githubusercontent.com/8935235/42855959-84b6ab3e-8a75-11e8-8643-96832f1e72b0.png)

**Comment by denghongcai** [comment]
https://github.com/ali-sdk/ali-ons/blob/master/example/config.js

set your env first
