### ISSUE TITLE
How to send a messages with delay?

### ISSUE THREAD

**Issue by daCapricorn** [ali-sdk/ali-ons#4]
Message#delayTimeLevel? milliseconds?

**Comment by gxcsoccer** [comment]
not milliseconds, just a level, like 0, 1, 2.   0 mean no delay.  it usually use in retry message

**Comment by clChenLiang** [comment]
I found in the `Message` type , can set the delayTimeLevel, and the comment show use milliseconds. And I tried with different Level from 0 - 15 , almost similar equal with a `minute` by one level up.
It's right ?
