### ISSUE TITLE
怀疑存在内存泄漏

### ISSUE THREAD

**Issue by peng-ran** [ali-sdk/ali-ons#41]
背景：2.0.4版本线上环境多个ons消费端服务集体OOMKill。
现象：多个消费者服务启动时间相同，但大约8-9小时后集体OOM，可确定无消息处理的消费者也会OOM。
测试：
1、ali-ons 2.0.4
2、只启动消费端服务，不生产消息进行测试且消费端服务只启动ons消费者subscribe，无任何其它逻辑。
3、服务刚启动时50M，17个小时后稳定在225-230M，高峰283M，测试环境容器限制最大300M，超过则重启服务；
目前看，在跑几个小时就该溢出了，所以怀疑这个版本仍然存在内存泄漏的问题或是ali-ons是否有最低内存要求？ 麻烦作者看看，谢谢。

**Comment by denghongcai** [comment]
总共才300M内存，Node.js 应用崩了很正常吧

可以用下 alinode 分析下你应用的内存状况

**Comment by peng-ran** [comment]
@denghongcai  谢谢，但是经过测试和观察内存情况我们认为2.0.4确实存在内存泄漏问题，后来我们更换到3.0.0版本，问题解决，内存分配和释放正常且服务内存稳定再50-110以内。
