### ISSUE TITLE
如何发送分区顺序消息

### ISSUE THREAD

**Issue by zhangwenzhao** [ali-sdk/ali-ons#5]
RT

**Comment by zhangwenzhao** [comment]
@gxcsoccer 能说明下吗？

**Comment by gxcsoccer** [comment]
@zhangwenzhao 不太明白，你能给一个具体的例子吗？

**Comment by zzjin23** [comment]
@gxcsoccer Java 中发送分区顺序消息的例子 https://help.aliyun.com/document_detail/49323.html

**Comment by gxcsoccer** [comment]
@zzjin23 好我看一下，后续支持

**Comment by wanming** [comment]
https://github.com/luoyjx/ali-ons/commit/22db41d3da66dc37c6c6d4653b4cefdd3ac74fd8 这个可行吗

**Comment by gxcsoccer** [comment]
use this [issue](https://github.com/ali-sdk/ali-ons/issues/40) for tracking

thx a lot
