### ISSUE TITLE
不支持公网的消息队列吗？

### ISSUE THREAD

**Issue by qinyang912** [ali-sdk/ali-ons#59]
![image](https://user-images.githubusercontent.com/5723181/53103225-2aa77800-3568-11e9-8fb3-8941ed9a42ea.png)
你好，我在用公网的消息队列做测试，发消息的时候，一直在报公网的接入点无法正常访问。是我的使用方式有问题吗？翻遍了文档，也找不到具体问题在哪里。请求解答
![image](https://user-images.githubusercontent.com/5723181/53103635-f2ed0000-3568-11e9-94da-274310296e14.png)

**Comment by denghongcai** [comment]
默认支持 https://www.aliyun.com/product/rocketmq?spm=5176.8142029.digitalization.38.e9396d3eExzYMT

自己修改 brokerAddr 后可以支持任意 RocketMQ 作为服务端的消息队列服务

**Comment by qinyang912** [comment]
@denghongcai 你好，谢谢这么快回复。brokerAddr和onsAddr有什么区别吗？

**Comment by denghongcai** [comment]
就是 onsAddr https://github.com/ali-sdk/ali-ons/blob/master/lib/client_config.js#L19

我是老词顺口了= =
