### ISSUE TITLE
支持消费者拉取消息吗？

### ISSUE THREAD

**Issue by CoCoyh** [ali-sdk/ali-ons#63]
@gxcsoccer 为了控制消费速率，有个需求是主动拉取消息数量，这个现在有支持吗？

**Comment by CoCoyh** [comment]
@denghongcai

**Comment by denghongcai** [comment]
目前只支持 PushConsumer，不支持 PullConsumer 模式

https://github.com/ali-sdk/ali-ons/blob/master/lib/consumer/mq_push_consumer.js#L43

可以通过设置流控相关配置的方式来控制消费速率

**Comment by gxcsoccer** [comment]
PullConsumer 暂时没有计划做，后面可以加一个 API 来暂停消费，用来控制速率

**Comment by CoCoyh** [comment]
@denghongcai

**Comment by gxcsoccer** [comment]
@CoCoyh 你可以提下希望怎么主动拉取，最好能提供伪代码，就是你想怎么用
