### ISSUE TITLE
发布和消费消息都会报错，topic找不到

### ISSUE THREAD

**Issue by CoCoyh** [ali-sdk/ali-ons#70]
![15_21_01__03_29_2019](https://user-images.githubusercontent.com/24558814/55215977-71a71e00-5236-11e9-8dc2-2b9fb9cc33be.jpg)
@denghongcai @gxcsoccer 在阿里云控制台上新建了Topic的，前两天测试都是好的，能帮忙看下问题吗？

**Comment by CoCoyh** [comment]
上图的左边是producer，右侧是consumer

**Comment by gxcsoccer** [comment]
@CoCoyh 啥原因？可以写到这里，给后面同学提供参考

**Comment by CoCoyh** [comment]
@gxcsoccer 要在订阅的topic前面加上实例ID，格式:
`instanceId%topic`
说明instanceId是阿里云上的rocketmq实例ID
