### ISSUE TITLE
getTopicRouteInfoFromNameServer提示Topic route info不存在

### ISSUE THREAD

**Issue by joyeekk** [ali-sdk/ali-ons#90]
RocketMq已经设置了autoCreateTopicEnable=true，即自动创建不存在的topic。
但是使用该SDK给一个不存在的topic发送消息时，还是会提示: [mq:client_api] get Topic [xxx] RouteInfoFromNameServer is not exist value。

**Comment by FourLeafClover** [comment]
怎么解决的？
